name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  test:
    name: "pytest (Python ${{ matrix.python-version}})"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Make sure 'sut' (under src/) is importable by tests
      - name: configure PYTHONPATH
        run: echo "PYTHONPATH=src" >> $GITHUB_ENV

      - name: Run full test suite
        run: |
          mkdir -p test-results
          pytest -q --junitxml=test-results/pytest.xml

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-${{ matrix.python-versoin }}
          path: test-results/pytest.xml
